### ISSUE TITLE
How to close 5GHZ

### ISSUE THREAD

**Issue by SSY-C** [morrownr/8821cu-20210118#39]
Hello,
I want to use 2.4GHz only, when I changed the "#define CONFIG_IEEE80211_BAND_5GHZ 1" to "0" in the drv_conf.h and install the driver, the scan results is none.

**Comment by morrownr** [comment]
Hi @SSY-C 

I'm too busy to look at this today but if you can describe what you are trying to accomplish and why, there might be an easier solution.

Regards,

Nick

**Comment by fishears** [comment]
In the interim can't you do this in on the system side in connection settings by selecting the BSSID associated with the 2,412Mhz channel?
