### ISSUE TITLE
(solved) Activate CONFIG_BEAMFORMING for MU-MIMO

### ISSUE THREAD

**Issue by ARiber** [morrownr/8821cu-20210118#5]
In the old driver version "CONFIG_BEAMFORMING" was activated so that MU-MIMO is supported.
In the new driver this is not activated yet.

Should activate it in 
include/autoconf.h

**Comment by morrownr** [comment]
Hi @ARiber 

> Should activate it in include/autoconf.h

No, unless you want to become your own tech support.

Go to your driver directory and run the following:

```
sudo ./edit-options.sh
```
Scroll down to the beamforming section. Read. You will probably want `10`. Make the appropriate change in the `options` line.

I did not remove support, I simply changed the default based on reports over time.

Regards
