### ISSUE TITLE
Cannot connect to 5ghz band

### ISSUE THREAD

**Issue by ydhnwb** [morrownr/8821cu-20210118#50]
Hi sir. your repo was amazing, but I have one little problem.
I have TOTOLINK AC650 dual band, it works to detect all my wifi modem with different ssid (2 ssid, 2.4ghz and 5ghz).

I can connect to 2.4Ghz network, but not on 5Ghz. It shows authentication problem but no, I think my auth is correct.

I already set country region but didnt solve the problem.

both ssid using wpa2-psk-aes

**Comment by ydhnwb** [comment]
I changed the auth type on my modem to WPA. after that it connect successfully.

I think I'll close this since it solve my problem.

But connect to 5Ghz and WPA2 is really wanted

**Comment by morrownr** [comment]
Hi @ydhnwb 

> I changed the auth type on my modem to WPA. after that it connect successfully.

I haven't seen any problems like this with this driver. You do want at least `wpa2-psk-aes`.

This driver has been running well with WPA3 here. It is not clear what the problem could be but I will keep an eye out.

Nick
